import Foundation

public enum PostingRulesUpdateLedgerRequestRulesItemKey: String, Codable, Hashable, CaseIterable, Sendable {
    case salesReceivable = "sales.receivable"
    case salesRevenueProducts = "sales.revenueProducts"
    case salesRevenueServices = "sales.revenueServices"
    case salesVatPayable = "sales.vatPayable"
    case salesAdvancesReceived = "sales.advancesReceived"
    case purchasesPayables = "purchases.payables"
    case purchasesVatReceivable = "purchases.vatReceivable"
    case purchasesGoodsForResale = "purchases.goodsForResale"
    case purchasesDefaultExpense = "purchases.defaultExpense"
    case purchasesPrepaidExpenses = "purchases.prepaidExpenses"
    case inventoryCogs = "inventory.cogs"
    case inventoryStock = "inventory.stock"
    case productionLaborApplied = "production.laborApplied"
    case productionScrap = "production.scrap"
    case bankFxGain = "bank.fxGain"
    case bankFxLoss = "bank.fxLoss"
    case settlementsFees = "settlements.fees"
    case settlementsCommissionRevenue = "settlements.commissionRevenue"
    case settlementsSellerPayable = "settlements.sellerPayable"
    case settlementsSuspense = "settlements.suspense"
    case revenueDeferredIncome = "revenue.deferredIncome"
    case revenueContractAsset = "revenue.contractAsset"
    case revenueRefundLiability = "revenue.refundLiability"
    case assetsDisposalGain = "assets.disposalGain"
    case assetsDisposalLoss = "assets.disposalLoss"
    case assetsDisposalProceeds = "assets.disposalProceeds"
    case cashAdvances = "cash.advances"
    case closingRetainedEarnings = "closing.retainedEarnings"
}