import Foundation

/// Jurisdiction the company is registered in (immutable after creation)
public enum PostV1AccountCompaniesCreateRequestCountryCode: String, Codable, Hashable, CaseIterable, Sendable {
    case at = "AT"
    case be = "BE"
    case bg = "BG"
    case cy = "CY"
    case cz = "CZ"
    case de = "DE"
    case dk = "DK"
    case ee = "EE"
    case es = "ES"
    case fi = "FI"
    case fr = "FR"
    case gr = "GR"
    case hr = "HR"
    case hu = "HU"
    case ie = "IE"
    case it = "IT"
    case lt = "LT"
    case lu = "LU"
    case lv = "LV"
    case mt = "MT"
    case nl = "NL"
    case pl = "PL"
    case pt = "PT"
    case ro = "RO"
    case se = "SE"
    case si = "SI"
    case sk = "SK"
    case `is` = "IS"
    case li = "LI"
    case no = "NO"
}