import Foundation

/// An event type, or "*" for every event
public enum SubscriptionsUpdateWebhooksRequestEventsItem: String, Codable, Hashable, CaseIterable, Sendable {
    case agreementInvoiceGenerated = "agreement.invoice_generated"
    case bankFeedSynced = "bank_feed.synced"
    case filingFailed = "filing.failed"
    case filingRejected = "filing.rejected"
    case goodsReceiptPosted = "goods_receipt.posted"
    case intercompanyInvoiceMirrored = "intercompany.invoice_mirrored"
    case itemCreated = "item.created"
    case itemDeleted = "item.deleted"
    case itemUpdated = "item.updated"
    case leadConverted = "lead.converted"
    case leadCreated = "lead.created"
    case partnerInquiryCreated = "partner_inquiry.created"
    case payrollRunApproved = "payroll_run.approved"
    case posReportCreated = "pos_report.created"
    case priceListUpdated = "price_list.updated"
    case purchaseInvoicePaid = "purchase_invoice.paid"
    case purchaseInvoiceRegistered = "purchase_invoice.registered"
    case purchaseOrderApproved = "purchase_order.approved"
    case purchaseOrderReceived = "purchase_order.received"
    case refundLiabilityActual = "refund_liability.actual"
    case refundLiabilityTruedUp = "refund_liability.trued_up"
    case reportCompleted = "report.completed"
    case reportFailed = "report.failed"
    case revenueRecognitionModified = "revenue_recognition.modified"
    case revenueRecognitionPosted = "revenue_recognition.posted"
    case saleInvoiceEinvoiceSent = "sale_invoice.einvoice_sent"
    case saleInvoiceIssued = "sale_invoice.issued"
    case saleInvoicePaid = "sale_invoice.paid"
    case saleInvoicePeppolSent = "sale_invoice.peppol_sent"
    case saleInvoiceSent = "sale_invoice.sent"
    case salesOrderCreated = "sales_order.created"
    case salesOrderFulfilled = "sales_order.fulfilled"
    case settlementImported = "settlement.imported"
    case settlementPosted = "settlement.posted"
    case settlementUpdated = "settlement.updated"
    case stockChanged = "stock.changed"
    case stockReorderNeeded = "stock.reorder_needed"
    case vatReviewOpened = "vat_review.opened"
    case vatReviewResolved = "vat_review.resolved"
    case all = "*"
}